# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XkLV6T11b-IQF1UZM8Ignup7drE8Bf_Y
"""

import streamlit as st
import numpy as np
import tensorflow as tf
from PIL import Image
import cv2

# Load model
@st.cache_resource
def load_model():
    model = tf.keras.models.load_model('/content/drive/MyDrive/crop_disease_model.h5')
    return model

model = load_model()

# Title
st.title("🌾 Crop Disease Detection")

# Upload image
uploaded_file = st.file_uploader("Upload a leaf image", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert('RGB')
    st.image(image, caption='Uploaded Image', use_column_width=True)

    # Preprocess
    img = image.resize((224, 224))
    img_array = np.expand_dims(np.array(img)/255.0, axis=0)

    # Predict
    prediction = model.predict(img_array)
    predicted_class = np.argmax(prediction)

    st.success(f"Predicted class ID: {predicted_class}")